name: Deploy Node Backend to EC2

on:
push:
branches:
- main

jobs:
deploy:
runs-on: ubuntu-latest

strategy:
  matrix:
    node-version: [18.x]

steps:
  - name: Checkout Repository
    uses: actions/checkout@v4

  - name: Use Node.js
    uses: actions/setup-node@v3
    with:
      node-version: ${{ matrix.node-version }}
      cache: npm

  - name: Install Dependencies
    run: npm install

  - name: Deploy to EC2
    uses: appleboy/ssh-action@v1.0.3
    with:
      host: ${{ secrets.EC2_HOST }}
      username: ${{ secrets.EC2_USER }}
      key: ${{ secrets.EC2_KEY }}
      script: |
        cd ~/anteso-backend
        git pull origin main
        npm install
        echo "${{ secrets.BACKENDENV }}" > .env
        pm2 restart anteso-backend || pm2 start index.js --name anteso-backend
```
