name: Deploy Node Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd ~/anteso-backend

            git fetch origin
            git reset --hard origin/main

            npm install

            echo "${{ secrets.BACKENDENV }}" > .env

            pm2 delete anteso-backend || true
            pm2 start index.js --name anteso-backend
            pm2 save
